# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: HCLTechnologies.ApplicationSecurity-VSTS.custom-build-release-task.HCLAppScan@1
  inputs:
    AppSecTestService: 'HCLServiceConnection24062022'
    applications: '67daffae-525e-41a2-8167-2b04b73df83b'
    scanname: 'nnn'
    scantype: 'static'