# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

  - task: HCLTechnologies.ApplicationSecurity-VSTS.custom-build-release-task.HCLAppScan@2
    inputs:
      AppSecTestService: 'HCLServiceConnection24062022'
      applications: 'f5199746-677c-4270-8274-2d2791e26036'
      scanname: 'rvpazure111'
      scantype: 'static'