# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'HCLServiceConnection24062022'
    applications: 'a88b9941-dd95-42da-a3bc-9fc640a1fabb'
    scanname: 'test'
    scantype: 'static'
    
    - task: HCLAppScanOnCloud@2
      inputs:
        AppSecTestService: 'HCLServiceConnection24062022'
        applications: 'f5199746-677c-4270-8274-2d2791e26036'
        scanname: 'test'
        scantype: 'static'